### PR TITLE
Move from `bluepy` to `bleak`

### PR DESCRIPTION
**Pull request by qiz-li**
Hi! It looks like the new Home Assistant [update](https://www.home-assistant.io/blog/2022/07/06/release-20227/) phased out `bluepy`, and, as a result, this library no longer works with Home Assistant. I am not very familiar with BLE. However, I've made some tweaks to migrate to `bleak`. Hopefully, this can help move in the right direction if not get the component back up. Thanks.

### CODE REVIEW

**Comment by qiz-li** [comment]
I realized it is perhaps better to initiate and sustain the connection to the Switchmate rather than connecting for each update or command. This a lot closely resembles the original code. However, I am not exactly sure how Home Assistant was able to establish the initial connection without explicitly calling the `_connect` method?

**Comment by Danielhiversen** [comment]
>However, I am not exactly sure how Home Assistant was able to establish the initial connection without explicitly calling the _connect method?

It is always called during _sendpacket

https://github.com/Danielhiversen/pySwitchmate/blob/cbfefe4a45a34f042de9e9ef5e98bd73a0eb08f9/switchmate/__init__.py#L61

**Comment by qiz-li** [comment]
But initially when trying to send the packet, wouldn't an `AttributeError` be thrown because `self._deivce` is still `None` as it was never initialized as a client?

https://github.com/Danielhiversen/pySwitchmate/blob/e6caa8ac3d8612093e3a3fe3a71e5fdfd408e921/switchmate/__init__.py#L46

**Comment by Danielhiversen** [comment]
Attribute error is captured here:
https://github.com/Danielhiversen/pySwitchmate/blob/master/switchmate/__init__.py#L63

Any improvements are very appreciated.

**Comment by Danielhiversen** [comment]
Plea also update 
https://github.com/Danielhiversen/pySwitchmate/blob/master/setup.py#L6

**Comment by qiz-li** [comment]
> Attribute error is captured here: 
> https://github.com/Danielhiversen/pySwitchmate/blob/e6caa8ac3d8612093e3a3fe3a71e5fdfd408e921/switchmate/__init__.py#L63

I see! I completely overlooked it.

**Comment by qiz-li** [comment]
I have made some final changes. There seems to be some issue with the formatting, but I am not sure why because the code is formatted with Black. I have tested the library on the newest 2022.7.3 version of Home Assistant with both the original and the newer slim toggle switches. This should also resolve #9. If it looks good, please consider merging. Thanks, Daniel!

**Comment by hackthis02** [comment]
I am interested in testing this but as yet have found any documentation on how to sideload this on my home assistant instance. Could you point me in the right direction?

**Comment by Scags104** [comment]
> I am interested in testing this but as yet have found any documentation on how to sideload this on my home assistant instance. Could you point me in the right direction?

Me as well. This is causing a significant impact on my HA installation to the point i cant even reboot because the "config" is invalid

**Comment by theocoutu** [comment]
> > I am interested in testing this but as yet have found any documentation on how to sideload this on my home assistant instance. Could you point me in the right direction?
> 
> Me as well. This is causing a significant impact on my HA installation to the point i cant even reboot because the "config" is invalid

I couldn't get it to work, but what I did was:

Download the three files at 
 https://github.com/home-assistant/core/tree/dev/homeassistant/components/switchmate
and put them in
 config/custom-components/switchmate
and then edit manifest.json:

Change the line
  "requirements": ["pySwitchmate==0.4.6"],
to instead read
  "requirements": ["pySwitchmate @ git+https://github.com/qiz-li/pySwitchmate#bleak-conversion],

**Review by Danielhiversen — APPROVED** [review]
Thanks 👍

**Comment by qiz-li** [comment]
> > > I am interested in testing this but as yet have found any documentation on how to sideload this on my home assistant instance. Could you point me in the right direction?
> > 
> > 
> > Me as well. This is causing a significant impact on my HA installation to the point i cant even reboot because the "config" is invalid
> 
> I couldn't get it to work, but what I did was:

Because the library was updated to Bleak, the Home Assistant component has to be updated to work with asyncio. However, if anyone wants to do some testing or a quick fix, I've uploaded the code [here](https://github.com/qiz-li/switchmate). Please let me know if there are any issues. I am hoping to open a PR soon to update the official component.

**Comment by Scags104** [comment]
> 

This seemed to work as im back online with my switchmate but is it possible the `flip_on_off` function is no longer working? Seems like the switch is always on, if i toggle it off, it toggles right back on.

Thanks

**Comment by hackthis02** [comment]
> 
> This seemed to work as im back online with my switchmate but is it possible the `flip_on_off` function is no longer working? Seems like the switch is always on, if i toggle it off, it toggles right back on.
> 
> Thanks

I'm seeing this too. I set my `flip_on_off` to 0 and turned my switch around and it's displaying correctly in the UI now.

**Comment by qiz-li** [comment]
You're right! I made a mistake. The `if` statement when checking the state doesn't evaluate as I expected. The fix should be #13. Thanks.

https://github.com/Danielhiversen/pySwitchmate/blob/228f6fb515d1d96cb8b00e649f138988aaf176be/switchmate/__init__.py#L76-L81

**Pull request merged**
